CREATE OR REPLACE DATABASE DEV_<<DBS>>_<<DATABASE_NAME>> CLONE KEA_<<DBS>>;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TABLES IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STAGES IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL TASKS IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL STREAMS IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ALL FILE FORMATS IN DATABASE  DEV_<<DBS>>_<<DATABASE_NAME>> TO ROLE DATA_ENGINEER REVOKE CURRENT GRANTS;
