# This is a basic workflow to help you get started with Actions

name: Clone Snowflake Database

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      SandBox:
        description: 'Your Sandbox Name'
        required: true
        default: 'Dev'
        type: choice
        options:
        - SANDBOX_SAMI
        - SANDBOX_JUN
        - SANDBOX_ROMENIA
      DBS:
        description: 'Environment to run tests against'
        required: true
        default: 'Dev'
        type: choice
        options:
        - RAW
        - RAW+REFINED
        - RAW+REFINED+PUBLISHED
env:
  SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
  SNOWSQL_PASSWORD: ${{ secrets.SNOWSQL_PASSWORD }}
  
jobs:
  Clone-the-databases:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "box: $SandBox"
          echo "DBs: $DBS"
        env:
          YourSandbox: ${{ inputs.SandBox }}
          Databases: ${{ inputs.DBS }}
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up snowsql
        uses: actions/setup-python@v2
        with:
         python-version: 3.7

      - name: Install snowsql
        run: |
          python -m pip install snowsql

      - name: Clone database
        run: |
         snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -c "clone database <source_database> to <target_database>;"
