# This is a basic workflow to help you get started with Actions

name: Clone Snowflake Database

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      SandBox:
        description: 'Your Sandbox Name'
        required: true
        default: 'Dev'
        type: choice
        options:
        - SANDBOX_SAMI
        - SANDBOX_JUN
        - SANDBOX_ROMENIA
      DBS:
        description: 'Environment to run tests against'
        required: true
        default: 'Dev'
        type: choice
        options:
        - RAW
        - RAW+REFINED
        - RAW+REFINED+PUBLISHED
env:
  SNOWSQL_DEST: ~/snowflake
  SNOWSQL_ACCOUNT:  ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PASSWORD }}
  
jobs:
  Clone-the-databases:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "box: $SandBox"
          echo "DBs: $DBS"
        env:
          YourSandbox: ${{ inputs.SandBox }}
          Databases: ${{ inputs.DBS }}
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Find and replace
        run: |
          sed -i 's/<<DATABASE_NAME>>/${{ inputs.SandBox }}/g' code.sql
          sed -i 's/<<DBS>>/${{ inputs.DBS }}/g' code.sql
          
        shell: pwsh
        
        # working-directory: ${{ inputs.working-directory }}

      - name: Download SnowSQL
        run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      - name: Install SnowSQL
        run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: Test installation
        run:  ~/snowflake/snowsql -v
      
      #- name: Execute SQL against Snowflake
      #  run:  ~/snowflake/snowsql -f code.sql;
        
      - name: Get schema against Snowflake
        run:  ~/snowflake/snowsql -f schema.sql | sed 's/\t/,/g' > schema.txt
        
      - name: Find and replace
        run: |
          sed -i 's/|/ /g' schema.txt
          
      - name: Apply Permission
        run:  ~/snowflake/snowsql -f schema.txt;
        
