# This is a basic workflow to help you get started with Actions

name: Clone Snowflake Database

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      SandBox:
        description: 'Your Sandbox Name'
        required: true
        default: 'Dev'
        type: choice
        options:
        - ADHAKAL
        - APURVA
        - CRYSTAL
        - DHAMO
        - JUN
        - ROMENIA
        - Ravi
        - SAMI
      DBS:
        description: 'Environment'
        required: true
        default: 'RAW'
        type: choice
        options:
        - RAW
        - REFINED
        - PUBLISHED
        - DISTRIPUTION
        - LANDING
        - INTEGRATION
        
env:
  SNOWSQL_DEST: ~/snowflake
  SNOWSQL_ACCOUNT:  ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PASSWORD }}
  
jobs:
  Clone-the-databases:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "box: $SandBox"
          echo "DBs: $DBS"
        env:
          YourSandbox: ${{ inputs.SandBox }}
          Databases: ${{ inputs.DBS }}
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Find and replace
        run: |
          sed -i 's/<<DATABASE_NAME>>/${{ inputs.SandBox }}/g' code.sql
          sed -i 's/<<DBS>>/${{ inputs.DBS }}/g' code.sql
          
        shell: pwsh
        
        # working-directory: ${{ inputs.working-directory }}

      - name: Download SnowSQL
        run:  curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      - name: Install SnowSQL
        run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: Test installation
        run:  ~/snowflake/snowsql -v
      
      # - name: Execute SQL against Snowflake
      # run:  ~/snowflake/snowsql -f code.sql;
        
      - name: Get all the stages against Snowflake
        run:  ~/snowflake/snowsql -f stage.sql | sed 's/\t/,/g' > stages.txt
        
      - name: Find and replace
        run: |
          sed -i 's/|/ /g' stages.txt
          sed -i 1d stages.txt
          sed -i 1d stages.txt
          sed -i 1d stages.txt
          sed -i 1d stages.txt
          sed -i 1d stages.txt
          sed -i '$ d' stages.txt
          sed -i '$ d' stages.txt
          sed -i 's/<<DATABASE_NAME>>/${{ inputs.SandBox }}/g' code.sql
          sed -i 's/<<DBS>>/${{ inputs.DBS }}/g' code.sql
          
      - name: Fix stages
        run:  ~/snowflake/snowsql -f stages.txt;
        
